[package]
name = "shooting_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_embedded_assets = "0.14.0"

serde.workspace = true
serde_json.workspace = true
rand.workspace = true

bevy.workspace = true
tungstenite.workspace = true

shooting_game_shared.path = "../shared"