[workspace]
members = ["game","backend","shared"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
rand = "0.9.2"

bevy = "0.17.2"

rocket_ws = "0.1.1"
tungstenite = "0.28.0"