[package]
name = "shooting_game_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5"

rocket_ws.workspace = true
serde.workspace = true
serde_json.workspace = true

shooting_game_shared.path = "../shared"
