[package]
name = "shooting_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true

serde.workspace = true
serde_json.workspace = true
rand.workspace = true

games-lib.workspace = true